// ===== PROJECT DATA =====
// To update: edit this file, add screenshots to /images/projects/
const projects = [
    {
        id: 1,
        title: "Growth in the Granite State",
        category: "Remote Sensing",
        type: "remote",
        tags: ["Landsat 8/9", "Change Detection", "TerrSet"],
        summary: "Analyzing urban expansion in New Hampshire's 3 largest cities over 10 years using Landsat satellite imagery and multitemporal change detection.",
        description: "This project analyzed urban expansion in Concord, Manchester, and Nashua, NH by comparing Landsat 8 imagery from 2014 with Landsat 9 imagery from 2024. True color composites were created using bands 2, 3, and 4, then pansharpened with the 15m panchromatic band for enhanced spatial resolution. A multitemporal composite was generated by overlaying bands with red/green/blue filters to highlight changes in development — magenta areas indicate 2014 land cover, green indicates 2024 growth. The analysis revealed significant expansion in Concord (~5% population growth) and Nashua (~4% growth), while Manchester showed a slight population decline (~1%) attributed to urban challenges. The project demonstrated how freely available satellite imagery can effectively monitor urban growth patterns for sustainable development and land management planning.",
        tools: ["Landsat 8/9", "TerrSet", "PANSHARPEN", "True Color Composites", "Multitemporal Analysis"],
        year: "2024",
        course: "GPH910 — Digital Image Processing",
        thumb: "images/projects/change-analysis.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 2,
        title: "Mapping Education and Wealth",
        category: "Spatial Analysis",
        type: "analysis",
        tags: ["ArcGIS Pro", "Census ACS", "Bivariate"],
        summary: "Exploring the spatial correlation between educational attainment and household wealth across Massachusetts municipalities.",
        description: "This project investigated the geographic relationship between educational attainment and household wealth across Massachusetts towns and cities. Using American Community Survey (ACS) census data, the analysis mapped multiple indicators including median household income, bachelor's degree attainment rates, and poverty levels at the municipal level. Bivariate mapping techniques revealed clear spatial patterns — communities with higher concentrations of advanced degrees consistently correlated with higher median incomes, with notable clustering in the Greater Boston suburbs and western Massachusetts college towns. The project produced a series of thematic maps illustrating these relationships and highlighting equity gaps across the Commonwealth.",
        tools: ["ArcGIS Pro", "Census ACS Data", "MassGIS", "Bivariate Mapping"],
        year: "2024",
        course: "GPH952 — Spatial Database Design & Analysis",
        thumb: "images/projects/education.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 3,
        title: "Salem Pantry: Mapping Food Access",
        category: "Spatial Analysis",
        type: "analysis",
        tags: ["R", "Census ACS", "Cluster Analysis"],
        summary: "GIS analysis for a non-profit food pantry — mapping user demographics, travel distances, and predicting underserved communities across Massachusetts.",
        description: "A comprehensive GIS analysis conducted for the Salem Pantry, a Salem-based non-profit working to ensure convenient access to healthy food. The project analyzed pantry-provided data including household size, location, income, language, and race to answer key questions: Who are the pantry users? Where are they coming from? Are there spatial clusters based on socioeconomic variables? Can we predict where to find potential pantry users by census block group across Massachusetts? Using MassGIS shapefiles and ACS census data (median household income, household size, language, race, population density, owner/renter status), the analysis calculated distances to pantry locations, identified user clusters, and built a predictive model to highlight underserved communities statewide. Results were delivered to the Salem Pantry board to inform decisions about visitor management and potential expansion.",
        tools: ["R", "ArcGIS Pro", "MassGIS", "Census ACS", "Cluster Analysis", "Predictive Modeling"],
        year: "2024",
        course: "GPH953 — Seminar in GIS Applications",
        thumb: "images/projects/salem-pantry.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 4,
        title: "Emergency Evacuation Route Planning",
        category: "Web App",
        type: "web",
        tags: ["Python", "arcpy", "FEMA", "Network Analysis"],
        summary: "Python-based geospatial workflow identifying optimal evacuation routes for Salem, MA by integrating FEMA flood zones and traffic congestion data.",
        description: "This project developed a geospatial workflow for identifying optimal evacuation routes in Salem, MA — a coastal city prone to hurricanes and flooding. Using Python's arcpy library, the analysis integrated three key datasets: MassGIS road network data with Annual Average Daily Traffic (AADT) volumes, FEMA flood zone boundaries, and Salem municipal boundaries. All datasets were reprojected to Massachusetts State Plane and clipped to the study area. A weighted routing system was created where roads with higher traffic volumes and greater flood risk received higher impedance weights, making them less favorable for evacuation. The output map visualizes the safest and most dangerous routes from a given starting point, with darker red lines indicating routes to avoid. The methodology is scalable and reproducible for other disaster-prone communities.",
        tools: ["Python", "arcpy", "ArcGIS Pro", "MassGIS", "FEMA Flood Data", "Network Analysis"],
        year: "2024",
        course: "GPH960 — Software Design & Programming in GIS",
        thumb: "images/projects/salem-evacuation.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 5,
        title: "Optimal EV Charging Station Siting",
        category: "Research",
        type: "analysis",
        tags: ["GIS-AHP", "MCDM", "EV Infrastructure"],
        summary: "Research proposal using GIS and multi-criteria decision making to identify optimal locations for EV charging infrastructure across Massachusetts.",
        description: "A comprehensive GIS research proposal addressing one of Massachusetts' key infrastructure challenges: strategically siting electric vehicle charging stations to meet the state's target of 900,000 EVs by 2030. The research reviews and applies spatial analytical techniques including Kernel Density Estimation (KDE), network analysis, and location-allocation models, combined with Multi-Criteria Decision Making (MCDM) frameworks like AHP and fuzzy DEMATEL. The proposal examines current infrastructure gaps — as of December 2024, Massachusetts had ~8,800 public charging ports but needs approximately 10,000 DC fast chargers, 35,000 Level 2 ports, and 700,000 residential/workplace chargers. The research incorporates equity considerations, analyzing how historically redlined and underserved neighborhoods are disproportionately lacking charging access. The literature review spans studies from Amsterdam, Birmingham UK, Ottawa, and Qingdao to build a methodology tailored to the Massachusetts context.",
        tools: ["ArcGIS Pro", "GIS-AHP", "KDE", "Network Analysis", "Location-Allocation", "Census Data"],
        year: "2025",
        course: "GPH904 — GIS Research",
        thumb: "images/projects/ev-research.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 6,
        title: "Central Campus Mapping",
        category: "Cartography",
        type: "map",
        tags: ["ArcGIS Pro", "Campus", "Cartography"],
        summary: "Detailed cartographic map of a university campus using high-resolution imagery and precise feature digitization.",
        description: "A cartographic mapping project featuring detailed digitization of a university campus. The project involved georeferencing high-resolution aerial imagery, digitizing building footprints, walkways, parking areas, and landscape features, and producing a polished reference map with proper cartographic elements including legend, scale bar, north arrow, and coordinate grid. The map demonstrates proficiency in geodatabase design, feature class management, and cartographic layout in ArcGIS Pro.",
        tools: ["ArcGIS Pro", "Georeferencing", "Digitization", "Cartographic Layout"],
        year: "2024",
        course: "GPH946 — Computer Cartography",
        thumb: "images/projects/central-campus.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 7,
        title: "Lynn, MA: Demographic Analysis",
        category: "Spatial Analysis",
        type: "analysis",
        tags: ["ArcGIS Pro", "Demographics", "Census"],
        summary: "Multi-layered demographic and spatial analysis of Lynn, Massachusetts examining population, housing, and socioeconomic patterns.",
        description: "A comprehensive demographic and spatial analysis of Lynn, Massachusetts — a diverse gateway city north of Boston. The project analyzed census data across multiple dimensions including population density, racial and ethnic composition, household income distribution, housing tenure, educational attainment, and language spoken at home. The analysis produced a series of thematic maps revealing spatial patterns of segregation, poverty concentration, and community characteristics at the census tract and block group level. The work provides a data-driven foundation for urban planning, community development, and resource allocation decisions in one of Massachusetts' most diverse municipalities.",
        tools: ["ArcGIS Pro", "Census ACS", "MassGIS", "Thematic Mapping"],
        year: "2025",
        course: null,
        thumb: "images/projects/lynn.png",
        liveUrl: null,
        repoUrl: null
    },
    {
        id: 8,
        title: "Lynnfield Cemetery GIS Database",
        category: "Database Design",
        type: "web",
        tags: ["PostGIS", "Database", "Municipal"],
        summary: "A GIS database system for managing and mapping burial plots at Forest Hill Cemetery for the Town of Lynnfield.",
        description: "A GIS database design and implementation project for the Town of Lynnfield's Forest Hill Cemetery. The project involved creating a spatial database to manage cemetery lot records, burial plot locations, and associated deeds. Historical cemetery maps and diagrams were georeferenced and digitized, veteran grave sites were incorporated from existing shapefiles, and burial records were cleaned, standardized, and linked to spatial features. The resulting system allows cemetery staff to query, visualize, and manage plot information spatially — a significant improvement over the previous paper-based record system. Delivered as a PostGIS database with a clean cartographic output.",
        tools: ["PostGIS", "ArcGIS Pro", "Georeferencing", "Database Design", "Python"],
        year: "2024",
        course: "GPH952 — Spatial Database Design & Analysis",
        thumb: "images/projects/lynnfield.png",
        liveUrl: null,
        repoUrl: null
    }
];

// ===== CATEGORY CONFIG =====
const categories = [
    { key: "all", label: "All" },
    { key: "map", label: "Cartography" },
    { key: "analysis", label: "Spatial Analysis" },
    { key: "web", label: "Web App / Database" },
    { key: "remote", label: "Remote Sensing" }
];

const typeLabels = {
    map: "MAP",
    analysis: "ANALYSIS",
    viz: "VIZ",
    web: "WEB / DB",
    remote: "REMOTE"
};

const typeClasses = {
    map: "type-map",
    analysis: "type-analysis",
    viz: "type-viz",
    web: "type-web",
    remote: "type-remote"
};

const typePlaceholders = {
    map: "\u{1F5FA}",
    analysis: "\u{1F4CA}",
    viz: "\u{1F4C8}",
    web: "\u{1F310}",
    remote: "\u{1F6F0}"
};
