"""Assemble the provenance manifest: metric -> file -> {source, dataset, refill}.

Resolution order per metric:
  1. metrics override (overrides.yml)
  2. column is in a side file        -> that file's fetch-script attribution
  3. column is baked into a geojson  -> external lehs-data-dive pipeline
  4. column is computed (derived)    -> recompute after refilling inputs
  5. otherwise                       -> unresolved (itself surfaced as a gap)
"""

import json
import os

from .. import config
from ..catalog import load_catalog
from . import extract

SCRIPTS_DIR = os.path.join(config.ROOT, "scripts")
GEO_FILE = "ma_academic_districts.geojson"

# Columns added by compute_correlations.compute_derived (computeDerivedMetrics).
_DERIVED_EXACT = {"diversity_index", "enroll_change_5yr", "enroll_change_10yr",
                  "teacher_rep_gap"}


def _is_derived(mid):
    return mid in _DERIVED_EXACT or "_gap" in mid or "gap_" in mid


def _load_overrides():
    import yaml
    p = config.OVERRIDES_PATH
    if os.path.exists(p):
        try:
            return yaml.safe_load(open(p, encoding="utf-8")) or {}
        except Exception:
            return {}
    return {}


def _file_to_script(scripts):
    """Invert writes -> {file: best_script}, preferring a naming-matched fetcher."""
    cands = {}
    for name, info in scripts.items():
        for f in info["writes"]:
            cands.setdefault(f, []).append(name)
    f2s = {}
    for f, names in cands.items():
        stem = (f.replace("ma_district_", "").replace("ma_muni_", "")
                 .replace(".json", "").replace(".geojson", ""))
        best = next((n for n in sorted(names) if n.startswith("fetch_") and stem in n), None)
        best = best or next((n for n in sorted(names) if n.startswith("fetch_")), None)
        f2s[f] = best or sorted(names)[0]
    return f2s


def build_manifest():
    catalog = load_catalog()
    scripts = extract.scan_scripts(SCRIPTS_DIR)
    col2files = extract.column_to_file(config.DATA)
    geo_cols = extract.geojson_columns(config.DATA)
    f2s = _file_to_script(scripts)
    overrides = _load_overrides()
    file_ov = overrides.get("files", {})
    metric_ov = overrides.get("metrics", {})

    by_file = {}

    def file_entry(fn):
        if fn in by_file:
            return
        sname = f2s.get(fn)
        sinfo = scripts.get(sname) if sname else None
        entry = {
            "fetch_script": f"scripts/{sname}" if sname else None,
            "upstream_source": sinfo["source"] if sinfo else None,
            "dataset_id": sinfo["dataset_id"] if sinfo else None,
            "vintage": sinfo["vintage"] if sinfo else None,
            "refill_command": (sinfo["refill"] if sinfo else None),
            "resolution": "docstring" if sinfo else "unresolved",
            "confidence": ("high" if (sinfo and sinfo["dataset_id"])
                           else "medium" if sinfo else "low"),
        }
        if fn in file_ov:                         # hand override wins
            entry.update(file_ov[fn])
            entry["resolution"] = "override"
            entry["confidence"] = "high"
        by_file[fn] = entry

    by_metric = {}
    unresolved = []
    for mid in catalog:
        if mid in metric_ov:
            by_metric[mid] = {"resolution": "override", **metric_ov[mid]}
            continue
        files = col2files.get(mid)
        if files:
            fn = sorted(files)[0]
            file_entry(fn)
            rec = {"file": fn, "ref": f"by_file/{fn}"}
            if len(files) > 1:
                rec["also_in"] = sorted(files)[1:]
            by_metric[mid] = rec
        elif mid in geo_cols:
            if GEO_FILE not in by_file:
                by_file[GEO_FILE] = {
                    "fetch_script": None,
                    "upstream_source": "lehs-data-dive pipeline (DESE joins), baked into the geojson",
                    "dataset_id": None, "vintage": None,
                    "refill_command": "(regenerated by the external lehs-data-dive pipeline)",
                    "resolution": "geojson-baked", "confidence": "medium",
                }
            by_metric[mid] = {"file": GEO_FILE, "ref": f"by_file/{GEO_FILE}"}
        elif _is_derived(mid):
            by_metric[mid] = {
                "resolution": "computed", "file": "<computed>",
                "refill_command": "recompute computeDerivedMetrics after refilling input columns",
            }
        else:
            unresolved.append(mid)
            by_metric[mid] = {"resolution": "unresolved"}

    return {
        "_meta": {
            "metrics_total": len(catalog),
            "metrics_resolved": len(catalog) - len(unresolved),
            "metrics_unresolved": len(unresolved),
            "scripts_scanned": len(scripts),
            "files_attributed": len(by_file),
        },
        "by_file": by_file,
        "by_metric": by_metric,
        "unresolved": sorted(unresolved),
    }


def write_manifest(path=None, manifest=None):
    m = manifest if manifest is not None else build_manifest()
    path = path or config.MANIFEST_PATH
    with open(path, "w", encoding="utf-8", newline="\n") as fh:   # LF on Windows too (eol=lf)
        json.dump(m, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return m


_CACHE = {}


def load_manifest():
    if "m" not in _CACHE:
        if os.path.exists(config.MANIFEST_PATH):
            _CACHE["m"] = json.load(open(config.MANIFEST_PATH, encoding="utf-8"))
        else:
            _CACHE["m"] = build_manifest()
    return _CACHE["m"]


def resolve(metric, manifest=None):
    """Denormalized provenance dict for a metric (or None)."""
    m = manifest or load_manifest()
    bm = m["by_metric"].get(metric)
    if not bm:
        return None
    ref = bm.get("ref", "")
    if ref.startswith("by_file/"):
        fn = ref.split("/", 1)[1]
        out = dict(m["by_file"].get(fn, {}))
        out["file"] = fn
        if bm.get("also_in"):
            out["also_in"] = bm["also_in"]
        return out
    return dict(bm)


# Fallback provenance for findings whose "metric" is a key field, geometry, or a
# synthetic cross-column check — so EVERY finding carries a source + refill path,
# not just catalog metrics. (Fixing is the goal; an un-attributed finding is dead weight.)
LAYER_SOURCES = {
    "school": {"upstream_source": "MA DESE School/District Profiles (public-school directory + school metrics)",
               "fetch_script": "scripts/fetch_school_metrics.py",
               "refill_command": "python scripts/fetch_school_metrics.py",
               "resolution": "layer", "confidence": "medium"},
    "colleges": {"upstream_source": "NCES IPEDS (institution directory + outcomes)",
                 "fetch_script": "scripts/fetch_ipeds_colleges.py",
                 "refill_command": "python scripts/fetch_ipeds_colleges.py",
                 "resolution": "layer", "confidence": "medium"},
    "private": {"upstream_source": "NCES Private School Survey (PSS)",
                "fetch_script": "scripts/fetch_private_schools.py",
                "refill_command": "python scripts/fetch_private_schools.py",
                "resolution": "layer", "confidence": "medium"},
    "childcare": {"upstream_source": "MA EEC licensed child-care directory (+ C3 grants)",
                  "fetch_script": "scripts/fetch_childcare.py",
                  "refill_command": "python scripts/fetch_childcare.py",
                  "resolution": "layer", "confidence": "medium"},
}

# Synthetic cross-column check ids -> the source whose data the check examines.
SYNTHETIC_SOURCES = {
    "grad_cohort_sum": {"upstream_source": "MA DESE Graduation Rates / cohort detail",
                        "fetch_script": "scripts/fetch_grad_detail.py",
                        "refill_command": "python scripts/fetch_grad_detail.py",
                        "resolution": "synthetic", "confidence": "medium"},
    "college_enroll_sum": {"upstream_source": "MA DESE Postsecondary Enrollment (NSC-derived)",
                           "fetch_script": "scripts/fetch_postsec_outcomes.py",
                           "refill_command": "python scripts/fetch_postsec_outcomes.py",
                           "resolution": "synthetic", "confidence": "medium"},
    "regional_hs": {"upstream_source": "MA DESE district directory (regional HS inclusion); built upstream in lehs-data-dive",
                    "fetch_script": None,
                    "refill_command": "add the regional district to the lehs-data-dive geojson build",
                    "resolution": "synthetic", "confidence": "low"},
}


def resolve_for_finding(obj, manifest=None):
    """Provenance for any finding object (has .level, .metric): catalog metric first,
    then synthetic-check id, then the finding's layer source."""
    m = manifest or load_manifest()
    r = resolve(obj.metric, m)
    if r and r.get("resolution") not in (None, "unresolved"):
        return r
    if obj.metric in SYNTHETIC_SOURCES:
        return dict(SYNTHETIC_SOURCES[obj.metric])
    if getattr(obj, "level", None) in LAYER_SOURCES:
        return dict(LAYER_SOURCES[obj.level])
    return r
