"""Render the registry into the fix-first worklist: gaps.md + gaps.csv.

Ranking = severity × fillability × impact, with a boost for never-acceptable
invariant violations so they float to the top. Every open row carries its upstream
source and the exact refill command — the worklist tells you what's wrong AND where
to go to fix it.
"""

import csv

from . import config
from .config import SEVERITY_W, NEVER_ACCEPTABLE


# ── ranking ──────────────────────────────────────────────────────────────────
def fillability(f):
    if f.status == "wontfix":
        return 0.05
    prov = f.provenance or {}
    if not prov.get("refill_command"):
        return 0.3
    if prov.get("confidence") == "low":
        return 0.6
    return 1.0


def impact(f):
    return 1.0 if f.scope == "*" else 0.5      # metric-wide outranks single-entity


def rank(f):
    score = SEVERITY_W.get(f.severity, 1) * fillability(f) * impact(f)
    if f.flag_code in NEVER_ACCEPTABLE and f.status == "open":
        score += 100                            # gate-failing invariants ride the top
    return round(score, 2)


# ── helpers ──────────────────────────────────────────────────────────────────
def _clip(s, n):
    s = " ".join(str(s or "").split())
    return s if len(s) <= n else s[:n - 1] + "…"


def _prov(f):
    p = f.provenance or {}
    return (p.get("upstream_source") or p.get("resolution") or "—",
            p.get("refill_command") or "—")


def _open_row(i, f):
    src, refill = _prov(f)
    scope = f.scope if f.scope != "*" else "—"
    return (f"| {i} | {f.severity} | {rank(f):.1f} | {f.level} | `{f.metric}` | "
            f"`{f.flag_code}` | {scope} | {_clip(f.detail, 72)} | "
            f"{_clip(src, 40)} | `{_clip(refill, 52)}` |")


# ── markdown ─────────────────────────────────────────────────────────────────
def render_md(findings):
    openf = sorted((f for f in findings if f.status == "open"),
                   key=lambda f: (-rank(f), f.fingerprint))
    inv = [f for f in findings if f.status == "investigating"]
    new = [f for f in findings if f.is_new and f.status in ("open", "investigating")]
    resolved = [f for f in findings if f.is_resolved]
    benign = [f for f in findings if f.status == "benign"]
    wontfix = [f for f in findings if f.status == "wontfix"]
    unresolved_prov = [f for f in openf if not (f.provenance or {}).get("refill_command")]

    L = ["# MA Education Atlas — Data Gap Worklist\n",
         "_Generated by `python -m scripts.analysis.gap_audit --emit-all`. "
         "This is a fix worklist, not just a report: every open row names its upstream "
         "source and the command to refill it._\n",
         f"**Open: {len(openf)}** · investigating: {len(inv)} · "
         f"benign: {len(benign)} · wontfix: {len(wontfix)} · "
         f"new this run: {len(new)} · resolved this run: {len(resolved)}\n"]

    L.append("\n## Open — fill worklist (ranked)\n")
    if openf:
        L.append("| # | Sev | Score | Level | Metric | Flag | Scope | What's wrong | Source | Refill |")
        L.append("|--:|---|--:|---|---|---|---|---|---|---|")
        L += [_open_row(i, f) for i, f in enumerate(openf, 1)]
    else:
        L.append("_None — every detected gap is benign, wontfix, or fixed._")

    if inv:
        L.append("\n## Investigating\n")
        L.append("| Metric | Flag | Scope | Note | Refill |")
        L.append("|---|---|---|---|---|")
        for f in inv:
            _, refill = _prov(f)
            L.append(f"| `{f.metric}` | `{f.flag_code}` | {f.scope} | "
                     f"{_clip(f.note, 50)} | `{_clip(refill, 52)}` |")

    if new:
        L.append(f"\n## 🆕 New since last run ({len(new)})\n")
        for f in sorted(new, key=lambda f: (-rank(f), f.fingerprint)):
            L.append(f"- **{f.severity}** `{f.flag_code}` `{f.metric}` "
                     f"(scope {f.scope}) — {_clip(f.detail, 90)}")

    if resolved:
        L.append(f"\n## ✅ Resolved this run ({len(resolved)})\n")
        L.append("_No longer raised — confirm it's a real fix, not a load fluke._\n")
        for f in resolved:
            L.append(f"- `{f.flag_code}` `{f.metric}` (scope {f.scope})")

    L.append("\n## Provenance gaps\n")
    if unresolved_prov:
        L.append("_Open findings with no known refill path — fill `provenance/overrides.yml`:_\n")
        for f in unresolved_prov:
            L.append(f"- `{f.metric}` ({f.flag_code})")
    else:
        L.append("_None — every open finding has a resolved source + refill command._")

    L.append(f"\n## Appendix A — Benign by design ({len(benign)})\n")
    L += _grouped_appendix(benign)
    L.append(f"\n## Appendix B — Won't fix ({len(wontfix)})\n")
    L += _grouped_appendix(wontfix)

    return "\n".join(L) + "\n"


def _grouped_appendix(items):
    if not items:
        return ["_None._"]
    by_reason = {}
    for f in items:
        by_reason.setdefault(f.reason or "(no reason)", []).append(f)
    out = []
    for reason, fs in sorted(by_reason.items()):
        mets = ", ".join(sorted(f"`{f.metric}`" for f in fs))
        out.append(f"- _{_clip(reason, 90)}_ — {mets}")
    return out


# ── csv ──────────────────────────────────────────────────────────────────────
def render_csv_rows(findings):
    rows = sorted((f for f in findings if f.status in ("open", "investigating")),
                  key=lambda f: (-rank(f), f.fingerprint))
    out = [["score", "severity", "status", "level", "metric", "flag_code", "scope",
            "detail", "source", "dataset_id", "refill_command", "fingerprint"]]
    for f in rows:
        p = f.provenance or {}
        out.append([rank(f), f.severity, f.status, f.level, f.metric, f.flag_code,
                    f.scope, f.detail, p.get("upstream_source"), p.get("dataset_id"),
                    p.get("refill_command"), f.fingerprint])
    return out


def write_reports(findings):
    with open(config.GAPS_MD, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_md(findings))
    with open(config.GAPS_CSV, "w", encoding="utf-8", newline="") as fh:
        csv.writer(fh, lineterminator="\n").writerows(render_csv_rows(findings))   # LF, not \r\n
